### ISSUE TITLE
Add option to switch to dark theme for text editor and topic preview

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [Infragistics/livewire#103] opened 2016-10-19 21:43 UTC
![image](https://cloud.githubusercontent.com/assets/11665978/19538771/abeb5ca6-9623-11e6-8747-e570b2755946.png)

**Comment by craigshoemaker** [comment] 2016-10-31 21:57
Duplicate of #16

**Closed by craigshoemaker** 2016-10-31 21:57 UTC
Labels: enhancement
