### ISSUE TITLE
Clicking on a link inside Livewire breaks the application

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/livewire#91] opened 2016-08-29 18:32 UTC
1. Open a file with a link like web-whats-new-in-2013-volume-1.adoc.
2. Click on a link to another topic (did this accidentally).

The Livewire application no longer displays the toolbar, the file, or the preview.

Unable to open the dev tools.

**Comment by craigshoemaker** [comment] 2016-08-30 22:38
duplicate of #63

**Comment by craigshoemaker** [comment] 2016-08-30 22:56
Clicking on the same link multiple times seems to eventually expose the error.

**Closed** 2016-11-01 21:48 UTC
Labels: bug, in progress
